language: node_js

node_js:
  - 12

script:
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./build
    keep_history: true
    target_branch: gh-pages
    verbose: true
    on:
      branch: master